name: Bake C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Lua 5.3
      run: |
        sudo apt update
        sudo apt install -y lua5.3 liblua5.3-dev
    - name: make
      run: make
    - name: Create version tag
      run: |
        VERSION="v$(date +%Y%m%d%H%M)"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $VERSION
        git push origin $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Bake Release ${{ env.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Bake Binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/bake
        asset_name: bake
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: bake
      run: ./build/bake
    - name: bake -B
      run: ./build/bake -B
    - name: bake cleanup
      run: ./build/bake clean
